(async()=>{
const $=id=>document.getElementById(id);const state={data:null,questions:[],filters:{keyword:'',term:[],session:[],examType:[],examHalf:[],booklet:'',category:'',departments:[],departmentUnclassified:false,diseases:[],diseaseUnclassified:false,learning:'',mode:'explore',sort:'number'},page:1,pageSize:10,view:'list',scope:'all',originId:null,currentId:null,lastAttemptId:null,studyView:false,searchSession:null};
let renderToken=0;let displayedAssets={};
const navStackKey='exam-study-minimal.navigation.v3';
const searchSessionKey=id=>`exam-study-minimal.search-session.v1.${id}`;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function uuid(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`}
function qs(o){const p=new URLSearchParams();Object.entries(o).forEach(([k,v])=>{if(Array.isArray(v)){v.forEach(x=>p.append(k,x))}else if(v!==''&&v!=null&&v!==false)p.set(k,v)});return p.toString()}
function persistSearchSession(){if(state.searchSession?.sessionId)sessionStorage.setItem(searchSessionKey(state.searchSession.sessionId),JSON.stringify(state.searchSession))}
function latestSearchSession(saved){if(!saved?.sessionId)return saved||null;try{const latest=JSON.parse(sessionStorage.getItem(searchSessionKey(saved.sessionId)));return ExamModel.mergeSearchSession(saved,latest)}catch{return saved}}
function snapshot(){persistSearchSession();return {scope:state.scope,filters:structuredClone(state.filters),sort:state.filters.sort,page:state.page,page_size:state.pageSize,scroll_anchor:getAnchor(),entry_id:uuid(),parent_entry_id:history.state?.entry_id||null,currentId:state.currentId,originId:state.originId,view:state.view,studyView:state.studyView,searchSession:state.searchSession?{sessionId:state.searchSession.sessionId}:null,scrollY:scrollY}}
function getAnchor(){const el=document.querySelector('.qrow[data-id]');return el?.dataset.id||null}
function pushNav(){const s=snapshot();history.pushState(s,'',location.pathname+'#'+routeHash());sessionStorage.setItem(navStackKey,JSON.stringify(s))}
function replaceNav(){const old=history.state||{};const s={...snapshot(),entry_id:old.entry_id||uuid(),parent_entry_id:old.parent_entry_id||null};history.replaceState(s,'',location.pathname+'#'+routeHash());sessionStorage.setItem(navStackKey,JSON.stringify(s))}
function routeHash(){if(state.view==='exercise')return `question=${encodeURIComponent(state.currentId)}`;const x={scope:state.scope,origin:state.originId||'',q:state.filters.keyword,term:state.filters.term,session:state.filters.session,type:state.filters.examType,half:state.filters.examHalf,category:state.filters.category,learning:state.filters.learning,sort:state.filters.sort,page:state.page,page_size:state.pageSize};state.filters.departments.forEach(d=>x['dept']=(x['dept']?x['dept']+',':'')+d);state.filters.diseases.forEach(d=>x['disease']=(x['disease']?x['disease']+',':'')+d);return qs(x)}
function restore(s){if(!s)return false;Object.assign(state,{scope:s.scope||'all',filters:{...(s.filters||state.filters),booklet:''},page:s.page||1,pageSize:s.page_size||10,currentId:s.currentId||null,originId:s.originId||null,view:s.view||'list',studyView:!!s.studyView,searchSession:latestSearchSession(s.searchSession)});render();setTimeout(()=>{if(s.scroll_anchor){document.querySelector(`[data-id="${CSS.escape(s.scroll_anchor)}"]`)?.scrollIntoView()}else scrollTo(0,s.scrollY||0)},0);return true}
window.addEventListener('popstate',e=>{if(!restore(e.state)){state.view='list';state.scope='all';state.currentId=null;render()}});

const raw=await ExamEditor.load();state.data=ExamAdapter.adapt(raw);state.questions=state.data.questions;ExamEditor.init(raw,updated=>{state.data=ExamAdapter.adapt(updated);state.questions=state.data.questions;renderList();});PackageManager.init();
const selections=v=>Array.isArray(v)?v.map(String):v==null||v===''?[]:[String(v)];
for(const [id,key,fixed] of [['f-term','term',[]],['f-session','session',['I','II','III']],['f-type','examType',['本試','追試']],['f-half','examHalf',['前半','後半']]]){
 const values=[...new Set([...fixed,...state.questions.map(q=>q[key]).filter(v=>v!=null).map(String)])].sort((a,b)=>fixed.length?fixed.indexOf(a)-fixed.indexOf(b):b.localeCompare(a,'ja',{numeric:true}));
 $(id).innerHTML=values.map(val=>`<label class="inline-check"><input type="checkbox" value="${esc(val)}">${esc(id==='f-term'?val+'期':id==='f-type'&&val==='追試'?'再試（追試）':val)}</label>`).join('');
}
for(const id of ['filter-details','department-details','disease-details']){const el=$(id),key='exam-study.ui.disclosure.'+id;const saved=sessionStorage.getItem(key);if(saved!==null)el.open=saved==='open';el.addEventListener('toggle',()=>sessionStorage.setItem(key,el.open?'open':'closed'));}


function readFilters(){state.filters.keyword=$('f-keyword').value.trim();state.filters.term=[...document.querySelectorAll('#f-term input:checked')].map(x=>x.value);state.filters.session=[...document.querySelectorAll('#f-session input:checked')].map(x=>x.value);state.filters.examType=[...document.querySelectorAll('#f-type input:checked')].map(x=>x.value);state.filters.examHalf=[...document.querySelectorAll('#f-half input:checked')].map(x=>x.value);state.filters.category=$('f-category').value;state.filters.learning=$('f-learning').value;state.filters.mode=$('f-mode').value;state.filters.sort=$('f-sort').value;state.pageSize=Number($('f-page-size').value);state.page=1;replaceNav();renderList()}
['f-keyword','f-term','f-session','f-type','f-half','f-category','f-learning','f-mode','f-sort','f-page-size'].forEach(id=>$(id).addEventListener(id==='f-keyword'?'input':'change',readFilters));
function bindFilterValues(){const f=state.filters;$('f-keyword').value=f.keyword||'';document.querySelectorAll('#f-term input').forEach(x=>x.checked=selections(f.term).includes(x.value));document.querySelectorAll('#f-session input').forEach(x=>x.checked=selections(f.session).includes(x.value));document.querySelectorAll('#f-type input').forEach(x=>x.checked=selections(f.examType).includes(x.value));document.querySelectorAll('#f-half input').forEach(x=>x.checked=selections(f.examHalf).includes(x.value));$('f-category').value=f.category||'';$('f-learning').value=f.learning||'';$('f-mode').value=f.mode||'explore';$('f-sort').value=f.sort||'number';$('f-page-size').value=String(state.pageSize||10)}

function scopeQuestions(){if(state.scope==='related'&&state.originId){const q=state.questions.find(x=>x.id===state.originId);const ids=new Set(ExamModel.relatedUnique(q).map(r=>r.question_id));return state.questions.filter(x=>ids.has(x.id))}if(state.scope==='same'&&state.originId){const q=state.questions.find(x=>x.id===state.originId);if(!q?.sameQuestionGroup)return [];return state.questions.filter(x=>x.sameQuestionGroup===q.sameQuestionGroup&&x.id!==q.id)}return state.questions}
function filtered(){let xs=ExamModel.filter(scopeQuestions(),state.filters,ExamStorage);const s=state.filters.sort;if(s==='last')xs.sort((a,b)=>(ExamStorage.summary(b.id).last||'').localeCompare(ExamStorage.summary(a.id).last||''));else if(s==='wrong')xs.sort((a,b)=>ExamStorage.summary(b.id).incorrect-ExamStorage.summary(a.id).incorrect||a.number-b.number);else xs.sort((a,b)=>a.number-b.number);return xs}
function classificationHtml(q){if(state.filters.mode==='exam')return '<span class="muted">試験形式：分類は非表示</span>';const deps=q.departments.map(d=>`<span class="badge ${d.confirmation_status==='provisional'?'provisional':''}">${esc(d.name)}</span>`).join('');let dis='';if(q.diseaseClassificationStatus==='not_applicable')dis='<span class="badge">疾患対象外</span>';else if(q.diseaseClassificationStatus==='unclassified')dis='<span class="badge">疾患未分類</span>';else dis=q.diseases.map(d=>`<span class="badge provisional">${esc(d.name)}</span>`).join('');return `<div class="badges">${deps}${dis}</div>`}
function relationCell(q){const rel=ExamModel.relatedUnique(q);const ss=ExamModel.sameStatus(q);const same=ss.known?(ss.count===0?'同一問題 0件':`同一問題 ${ss.count??''}`):'同一問題 未調査';return `<div><button class="relation-link same-link" data-id="${q.id}" ${ss.known&&ss.count===0?'disabled':''}>${same}</button></div><div>${rel.length?`<button class="relation-link rel-link" data-id="${q.id}">関連問題 ${rel.length}件</button>`:'関連問題 0件'}</div>${q.serialGroupId?'<span class="badge">連問</span>':''}`}
function renderList(){state.view='list';$('list-view').hidden=false;$('exercise-view').hidden=true;$('nav-back').hidden=!history.state?.parent_entry_id;$('go-home').hidden=state.scope==='all';$('list-title').textContent=state.scope==='related'?'関連問題一覧':state.scope==='same'?'同一問題一覧':'問題一覧';$('list-scope').textContent=state.scope==='all'?`${state.data.questions.length}問（登録済み冊子）`:`${state.originId} を起点・全試験`;const origin=state.originId&&state.questions.find(q=>q.id===state.originId);$('origin-card').hidden=!origin;$('origin-card').innerHTML=origin?`<strong>起点:</strong> ${esc(origin.displayLabel)}<br>${esc(origin.prompt)}`:'';
 renderFacets();const xs=filtered();const total=xs.length,pages=Math.max(1,Math.ceil(total/state.pageSize));if(state.page>pages)state.page=pages;const from=(state.page-1)*state.pageSize, page=xs.slice(from,from+state.pageSize);$('result-count').textContent=`${total}件`;$('start-search-sequence').disabled=total===0;$('page-info').textContent=`${state.page} / ${pages}`;$('prev-page').disabled=state.page<=1;$('next-page').disabled=state.page>=pages;
 $('question-list').innerHTML=page.length?page.map(q=>{const s=ExamStorage.summary(q.id);const cat=q.category==='general'?'一般問題':q.category==='clinical'?'臨床問題':'未判定';return `<div class="qrow" data-id="${q.id}"><div><div class="qpos">${esc(q.displayLabel)}</div><div class="muted">${esc(q.examDate||'実施日未登録')}</div><span class="badge ${q.categoryStatus==='provisional'?'provisional':''}">${cat}</span></div><div class="qtext">${esc((q.stem||q.prompt).slice(0,120))}</div><div>${classificationHtml(q)}</div><div>${relationCell(q)}<div class="muted">${s.attempted}回 / 正${s.correct} 誤${s.incorrect} 保留${s.hold}<br>${s.last?new Date(s.last).toLocaleString():'未回答'}</div></div><div class="actions"><button class="solve" data-id="${q.id}">解く</button><button class="secondary detail" data-id="${q.id}">解説を見る</button><button class="linklike edit-question" data-id="${q.id}">編集</button></div></div>`}).join(''):'<p>条件に一致する問題はありません。</p>';
 bindRows();bindFilterValues();renderActiveFilters();}
function renderFacets(){const depCounts=ExamModel.departmentCounts(scopeQuestions(),state.filters,ExamStorage,state.data.departmentMaster);const q=$('department-search').value.toLowerCase();$('department-options').innerHTML=depCounts.filter(d=>d.name.toLowerCase().includes(q)||d.department_id.includes(q)).map(d=>`<label><input type="checkbox" value="${d.department_id}" ${state.filters.departments.includes(d.department_id)?'checked':''}>${d.department_id}. ${esc(d.name)} <span class="muted">${d.count}件</span></label>`).join('');$('department-summary').textContent=state.filters.departments.length?`${state.filters.departments.length}件選択`:'未選択';$('department-unclassified').checked=state.filters.departmentUnclassified;
 const df=ExamModel.diseaseFacet(scopeQuestions(),state.filters,ExamStorage);$('disease-scope').textContent=`現在の検索結果 ${df.results.length}件から候補`;const s=$('disease-search').value.toLowerCase();$('disease-options').innerHTML=df.candidates.filter(d=>d.name.toLowerCase().includes(s)).map(d=>`<label><input type="checkbox" value="${d.disease_id}" ${state.filters.diseases.includes(d.disease_id)?'checked':''}>${esc(d.name)} <span class="muted">${d.count}件</span></label>`).join('')||'<div class="muted">候補なし</div>';$('disease-unclassified').checked=state.filters.diseaseUnclassified;
 const candIds=new Set(df.candidates.map(d=>d.disease_id));$('selected-disease-tags').innerHTML=state.filters.diseases.map(id=>{const d=state.data.diseaseMaster.find(x=>x.disease_id===id);return `<span class="chip">${esc(d?.name||id)}${candIds.has(id)?'':'（該当0件）'} <button class="linklike remove-disease" data-id="${id}">×</button></span>`}).join('');document.querySelectorAll('.remove-disease').forEach(b=>b.onclick=()=>{state.filters.diseases=state.filters.diseases.filter(x=>x!==b.dataset.id);replaceNav();renderList()});}
function renderActiveFilters(){const c=[];for(const [key,label] of [['term','期'],['session','試験'],['examType','本試/再試'],['examHalf','前半/後半']]){const chosen=selections(state.filters[key]);if(chosen.length)c.push(label+': '+chosen.join('・'));}if(state.filters.category)c.push(`問題区分:${state.filters.category}`);state.filters.departments.forEach(x=>c.push(`診療科:${x}`));state.filters.diseases.forEach(x=>c.push(`疾患:${state.data.diseaseMaster.find(d=>d.disease_id===x)?.name||x}`));if(state.filters.diseaseUnclassified)c.push('疾患未分類');$('active-filters').innerHTML=c.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}
$('department-search').oninput=renderFacets;$('disease-search').oninput=renderFacets;$('apply-departments').onclick=()=>{state.filters.departments=[...document.querySelectorAll('#department-options input:checked')].map(x=>x.value);state.filters.departmentUnclassified=$('department-unclassified').checked;state.page=1;replaceNav();renderList()};$('clear-departments').onclick=()=>{state.filters.departments=[];state.filters.departmentUnclassified=false;replaceNav();renderList()};$('apply-diseases').onclick=()=>{state.filters.diseases=[...document.querySelectorAll('#disease-options input:checked')].map(x=>x.value);state.filters.diseaseUnclassified=$('disease-unclassified').checked;state.page=1;replaceNav();renderList()};$('clear-diseases').onclick=()=>{state.filters.diseases=[];state.filters.diseaseUnclassified=false;replaceNav();renderList()};$('clear-filters').onclick=()=>{state.filters={keyword:'',term:[],session:[],examType:[],examHalf:[],booklet:'',category:'',departments:[],departmentUnclassified:false,diseases:[],diseaseUnclassified:false,learning:'',mode:'explore',sort:'number'};state.page=1;replaceNav();renderList()};$('prev-page').onclick=()=>{state.page--;replaceNav();renderList()};$('next-page').onclick=()=>{state.page++;replaceNav();renderList()};
function bindRows(){document.querySelectorAll('.edit-question').forEach(b=>b.onclick=()=>ExamEditor.open(b.dataset.id));document.querySelectorAll('.solve').forEach(b=>b.onclick=()=>startSearchSequence(b.dataset.id));document.querySelectorAll('.detail').forEach(b=>b.onclick=()=>openQuestion(b.dataset.id,true,false));document.querySelectorAll('.rel-link').forEach(b=>b.onclick=()=>openScope('related',b.dataset.id));document.querySelectorAll('.same-link:not([disabled])').forEach(b=>b.onclick=()=>openScope('same',b.dataset.id))}
function openScope(scope,id){const parent=snapshot();history.replaceState(parent,'',location.href);state.scope=scope;state.originId=id;state.page=1;state.searchSession=null;state.filters={keyword:'',term:[],session:[],examType:[],examHalf:[],booklet:'',category:'',departments:[],departmentUnclassified:false,diseases:[],diseaseUnclassified:false,learning:'',mode:'explore',sort:'number'};pushNav();renderList()}
async function sha256(buf){const h=await crypto.subtle.digest('SHA-256',buf);return [...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function showAsset(a,token){const box=$('figure-box'),status=$('figure-status');status.textContent='画像を読み込み中';try{const r=await fetch('./'+a.download_reference);if(!r.ok)throw new Error(`HTTP ${r.status}`);const buf=await r.arrayBuffer();const hash=await sha256(buf);if(token!==renderToken)return;if(hash!==a.sha256)throw new Error('SHA256不一致');ExamStorage.setAsset(a.asset_id,{state:'verified',hash,verifiedAt:new Date().toISOString()});const blob=new Blob([buf],{type:a.mime_type});const img=new Image();img.alt=a.alt||'設問画像';img.onload=()=>{if(token!==renderToken)return;displayedAssets[a.asset_id]={state:"displayed"};ExamStorage.setAsset(a.asset_id,{state:'displayed',displayedAt:new Date().toISOString()});status.textContent='画像を表示・拡大可能';updateSubmitReady();};img.onerror=()=>{if(token!==renderToken)return;displayedAssets[a.asset_id]={state:"failed"};ExamStorage.setAsset(a.asset_id,{state:'failed',reason:'decode/display error'});status.textContent='提示図あり・表示できません（再試行）';updateSubmitReady()};img.src=URL.createObjectURL(blob);box.appendChild(img);box.hidden=false}catch(e){if(token!==renderToken)return;displayedAssets[a.asset_id]={state:"failed"};ExamStorage.setAsset(a.asset_id,{state:'failed',reason:String(e)});status.textContent='提示図あり・表示できません（再試行）';box.hidden=true;updateSubmitReady()}}
function updateSubmitReady(){const q=current();if(!q)return;const ready=ExamModel.attemptReady(q,displayedAssets);$('submit').disabled=!ready.ready||state.studyView||!!state.lastAttemptId;$('skip').hidden=false;if(!ready.ready&&q.sourceImagePresence==='present')$('selection-hint').textContent='必要な提示図が表示確認されるまで通常演習の採点は開始できません。';else $('selection-hint').textContent=q.selectionCountInferred?'該当するものをすべて選択':q.requiredCount>1?`${q.requiredCount}つ選択`:'1つ選択';}
function current(){return state.questions.find(q=>q.id===state.currentId)}
function startSearchSequence(id){const ids=filtered().map(q=>q.id);if(!ids.length)return;openQuestion(id||ids[0],false,true,ids)}
function saveExerciseDraft(){if(state.view!=='exercise'||state.studyView||!state.searchSession||!state.currentId)return;ExamModel.updateSearchEntry(state.searchSession,state.currentId,{selected:[...document.querySelectorAll('input[name=choice]:checked')].map(x=>x.value),confidence:$('confidence').value||''});persistSearchSession()}
function openQuestion(id,studyView,startSequence=false,ids=null){const parent=snapshot();history.replaceState(parent,'',location.href);const fromExercise=state.view==='exercise';if(startSequence){state.searchSession={...ExamModel.createSearchSession(ids||filtered().map(q=>q.id),id),sessionId:uuid(),returnState:parent};persistSearchSession()}else if(!fromExercise)state.searchSession=null;state.view='exercise';state.currentId=id;state.studyView=!!studyView;pushNav();renderExercise(state.studyView)}
function renderSearchSequenceNav(){const active=!state.studyView&&state.searchSession?.sessionId,pos=active?ExamModel.searchPosition(state.searchSession,state.currentId):null;$('search-sequence-nav').hidden=!active;$('search-position-controls').hidden=!pos;if(!pos)return;$('search-position').textContent=pos.label;$('previous-question').disabled=!ExamModel.searchNeighbor(state.searchSession,state.currentId,-1);$('next-question').disabled=!ExamModel.searchNeighbor(state.searchSession,state.currentId,1)}
function showGradeResult(g){$('result').hidden=false;$('result').className='result '+(g.status==='correct'?'correct':g.status==='incorrect'?'incorrect':'hold');$('result').textContent=g.status==='correct'?'正解':g.status==='incorrect'?'不正解':`採点保留：${g.reason}`}
function renderExercise(studyView=false){renderToken++;displayedAssets={};state.studyView=studyView;$('list-view').hidden=true;$('exercise-view').hidden=false;$('nav-back').hidden=false;$('go-home').hidden=false;const q=current();if(!q){$('search-sequence-nav').hidden=true;$('exercise-view').hidden=true;history.back();return}$('position').textContent=q.displayLabel;$('code').textContent=q.code;$('progress').textContent=q.serialGroupId?`連問 ${q.serialOrder}`:`第${q.number}問`;$('confirmation').innerHTML=`校正: ${esc(q.calibrationStatus||'未確認')}<br>解答: ${esc(q.answerStatus)}<br>問題区分: ${esc(q.categoryStatus)}${q.categoryEvidence?`<br>${esc(q.categoryEvidence)}`:''}`;$('serial-context').hidden=!q.serialContext;$('serial-context').textContent=q.serialContext||'';$('stem').textContent=q.stem;$('prompt').textContent=q.prompt;$('choices').innerHTML=q.choices.map(c=>`<label class="choice"><input type="${q.requiredCount>1?'checkbox':'radio'}" name="choice" value="${c.label}"><strong>${c.label}</strong><span>${esc(c.text)}</span></label>`).join('');$('result').hidden=true;$('after-answer').hidden=true;$('confidence').value='';$('confidence').disabled=false;state.lastAttemptId=null;renderSearchSequenceNav();
 const entry=state.searchSession?.entries?.[q.id];if(entry){document.querySelectorAll('input[name=choice]').forEach(x=>x.checked=(entry.selected||[]).includes(x.value));$('confidence').value=entry.confidence||'';if(entry.attemptId&&entry.grade){state.lastAttemptId=entry.attemptId;document.querySelectorAll('input[name=choice]').forEach(x=>x.disabled=true);$('confidence').disabled=true;showGradeResult(entry.grade);renderAfter(q,entry.grade)}}const ready=ExamModel.attemptReady(q,displayedAssets);$('figure-box').hidden=true;$('figure-box').innerHTML='';$('figure-status').textContent=ready.message;if(q.sourceImagePresence==='present'){for(const a of ExamModel.visibleAssets(q))showAsset(a,renderToken)}updateSubmitReady();if(studyView){$('result').hidden=false;$('result').className='result hold';$('result').textContent='学習用閲覧：採点履歴は追加しません。';renderAfter(q,null)} }
$('submit').onclick=()=>{const q=current();if(state.studyView||state.lastAttemptId||!ExamModel.attemptReady(q,displayedAssets).ready)return;const selected=[...document.querySelectorAll('input[name=choice]:checked')].map(x=>x.value);const g=ExamGrader.grade(q,selected);if(g.status==='invalid'){$('result').hidden=false;$('result').className='result hold';$('result').textContent=g.reason;saveExerciseDraft();return}showGradeResult(g);const a={id:uuid(),questionId:q.id,questionRevisionId:q.questionRevisionId,answerVersionId:q.answerVersionId,selected,gradeStatus:g.status,confidence:$('confidence').value||null,answeredAtClient:new Date().toISOString(),committed:true};ExamStorage.addAttempt(a);state.lastAttemptId=a.id;if(state.searchSession){state.searchSession.entries[q.id]={selected:[...selected],confidence:a.confidence||'',attemptId:a.id,grade:structuredClone(g)};persistSearchSession()}document.querySelectorAll('input[name=choice]').forEach(x=>x.disabled=true);$('confidence').disabled=true;$('submit').disabled=true;renderAfter(q,g);replaceNav()};
function renderAfter(q,g){$('after-answer').hidden=false;const ex=q.explanation;if(!ex)$('explanation').textContent='解説は未登録';else if(ex.content_status==='load_failed')$('explanation').textContent='読込失敗・再試行';else{$('explanation').innerHTML=`<p><strong>${q.answerDisplay?'採用する扱い：'+esc(q.answerDisplay):q.answer.length?'記録された教室解答：'+esc(q.answer.join('・')):q.answerCandidate?.length?'解答候補（未確認）：'+esc(q.answerCandidate.join('・')):'教室解答は未確認'}</strong></p><p>${esc(ex.summary)}</p>${ex.options.map(o=>`<div class="option-reason"><strong>${o.label}${o.is_key?'（教室解答）':''}</strong> ${esc(o.reason)}</div>`).join('')}<div class="source-note">${esc(ex.source_kind||'')} / ${esc(ex.confirmation_status||'')}</div>`+(q.id==='57102fc8-beee-598a-a7d7-c3f5b5899079'?`<div class="steroid-note"><strong>ステロイド適応の補足</strong><br>教室解答は e のまま保持しています。ハイドロコルチゾン200 mg/日は敗血症性ショックで使用され得る治療であり、一律に不適切・禁忌とは扱いません。本文だけでは投与適応を決める経過が十分でなく、出題者説明と疑義照会結果は要確認です。</div>`:'')}
 const it=q.intent;if(!it)$('intent').textContent='出題意図は未登録';else if(it.content_status==='load_failed')$('intent').textContent='読込失敗・再試行';else $('intent').innerHTML=`<div class="badge">${esc(it.category||'')}</div>${(it.sections||[]).map(s=>`<h3>${esc(s.heading)}</h3><p>${esc(s.body)}</p>`).join('')}<div class="source-note">${esc(it.source_kind||'')}</div>`;$('learning-points').innerHTML=q.learningPoints.length?`<ul>${q.learningPoints.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'学習要点は未登録';
 const ss=ExamModel.sameStatus(q);$('answer-same-links').innerHTML=ss.known?'0件':'他試験は未調査（0件とは断定しません）';const rel=ExamModel.relatedUnique(q);$('answer-related-links').innerHTML=rel.length?`<div class="nav-list">${rel.map(r=>`<a href="#" data-relqid="${r.question_id}">${esc(r.destination?.display_label||r.question_id)} — ${esc((r.types||[]).join(' / '))}</a>`).join('')}</div>`:'0件';document.querySelectorAll('[data-relqid]').forEach(a=>a.onclick=e=>{e.preventDefault();saveExerciseDraft();replaceNav();openQuestion(a.dataset.relqid,false,false)});$('review-date').value=ExamStorage.reviews()[q.id]?.nextReviewDate||'';}
function moveSearchQuestion(delta){const id=ExamModel.searchNeighbor(state.searchSession,state.currentId,delta);if(!id)return;saveExerciseDraft();replaceNav();state.currentId=id;state.studyView=false;pushNav();renderExercise(false)}
function returnToSearchResults(){const target=state.searchSession?.returnState;if(!target)return;saveExerciseDraft();Object.assign(state,{scope:target.scope||'all',filters:{...(target.filters||state.filters),booklet:''},page:target.page||1,pageSize:target.page_size||10,currentId:null,originId:target.originId||null,view:'list',studyView:false,searchSession:null});pushNav();renderList();setTimeout(()=>{if(target.scroll_anchor)document.querySelector(`[data-id="${CSS.escape(target.scroll_anchor)}"]`)?.scrollIntoView();else scrollTo(0,target.scrollY||0)},0)}
$('previous-question').onclick=()=>moveSearchQuestion(-1);$('next-question').onclick=()=>moveSearchQuestion(1);$('return-search-results').onclick=returnToSearchResults;$('start-search-sequence').onclick=()=>startSearchSequence(filtered()[0]?.id);$('save-error').onclick=()=>{if(!state.lastAttemptId)return;ExamStorage.patchAttempt(state.lastAttemptId,{errorReasons:[...document.querySelectorAll('[name=error-reason]:checked')].map(x=>x.value),errorNote:$('error-note').value});};$('save-review').onclick=()=>{const q=current();ExamStorage.setReview(q.id,{nextReviewDate:$('review-date').value,updatedAt:new Date().toISOString()});};$('skip').onclick=()=>history.back();$('nav-back').onclick=()=>state.searchSession?returnToSearchResults():history.back();$('go-home').onclick=()=>{state.view='list';state.scope='all';state.originId=null;state.currentId=null;state.searchSession=null;pushNav();renderList()};
$('department-search').addEventListener('input',renderFacets);$('disease-search').addEventListener('input',renderFacets);
function render(){bindFilterValues();state.view==='exercise'?renderExercise(state.studyView):renderList()}
async function offlineBadge(){try{if(!navigator.serviceWorker.controller)throw Error();const d=await fetch('./deployment.json').then(r=>r.json());const c=await caches.open(d.cache_name);const ok=(await Promise.all(d.files.map(f=>c.match('./'+f)))).every(Boolean);$('offline-badge').textContent=ok?'本文・画像のオフライン保存完了':'オフライン保存は未完了';}catch{$('offline-badge').textContent='オフライン保存は未確認';}}
if('serviceWorker'in navigator){try{const registration=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});registration.update().catch(()=>{})}catch{}}setInterval(offlineBadge,10000);offlineBadge();bindFilterValues();if(!restore(history.state)){replaceNav();renderList();}
})();
