(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ExamModel=api;})(globalThis,function(){
function matchesSelection(value,selected){const choices=Array.isArray(selected)?selected:selected==null||selected===''?[]:[selected];return !choices.length||choices.some(x=>String(x)===String(value))}
function baseFilter(q,f,storage){if(f.keyword){const k=f.keyword.toLowerCase();const blob=[q.code,q.displayLabel,q.stem,q.prompt,...q.diseases.map(x=>x.name),...q.themes.map(x=>x.name)].join(' ').toLowerCase();if(!blob.includes(k))return false}if(!matchesSelection(q.term,f.term)||!matchesSelection(q.session,f.session)||!matchesSelection(q.examType,f.examType)||!matchesSelection(q.examHalf,f.examHalf))return false;if(f.booklet&&q.booklet!==f.booklet)return false;if(f.category==='__unclassified__'&&q.category!==null)return false;if(f.category&&f.category!=='__unclassified__'&&q.category!==f.category)return false;if(f.departmentUnclassified&&q.departments.length)return false;if(f.departments?.length&&!q.departments.some(d=>f.departments.includes(d.department_id)))return false;if(f.diseaseUnclassified&&q.diseaseClassificationStatus!=='unclassified')return false;if(f.diseases?.length&&!q.diseases.some(d=>f.diseases.includes(d.disease_id)))return false;if(f.theme==='__unclassified__'&&q.themes.length)return false;if(f.theme&&f.theme!=='__unclassified__'&&!q.themes.some(t=>t.theme_id===f.theme))return false;if(f.learning){const s=storage.summary(q.id);if(f.learning==='unanswered'&&s.attempted!==0)return false;if(f.learning==='answered'&&s.attempted===0)return false;if(f.learning==='ever_wrong'&&s.incorrect===0)return false}return true}
function filter(qs,f,storage){return qs.filter(q=>baseFilter(q,f,storage))}
function diseaseFacet(qs,f,storage){const results=filter(qs,f,storage);const map=new Map();results.forEach(q=>q.diseases.forEach(d=>{const x=map.get(d.disease_id)||{...d,count:0};x.count++;map.set(d.disease_id,x)}));return {results,candidates:[...map.values()].sort((a,b)=>a.name.localeCompare(b.name,'ja'))}}
function departmentCounts(qs,f,storage,master){const g={...f,departments:[],departmentUnclassified:false};const results=filter(qs,g,storage);return master.map(d=>({...d,count:results.filter(q=>q.departments.some(x=>x.department_id===d.department_id)).length}))}
function relatedUnique(q){const m=new Map();(q.related||[]).forEach(r=>{const id=r.question_id;const x=m.get(id)||{...r,types:[]};for(const t of (r.types||[]))if(!x.types.includes(t))x.types.push(t);m.set(id,x)});return [...m.values()]}
function sameStatus(q){if(q.sameQuestionGroup)return {known:true,count:null};if(q.sameQuestionSearchStatus==='not_assessed_across_exams')return {known:false,label:'未調査'};return {known:true,count:0}}
function visibleAssets(q){return (q.assets||[]).filter(a=>(a.role||'question_image')==='question_image')}
function attemptReady(q,assetStates){if(q.sourceImagePresence==='unknown')return {ready:false,state:'unknown',message:'提示図の有無を確認中'};if(q.sourceImagePresence==='none')return {ready:true,state:'none',message:'この問題に提示図はありません'};const assets=visibleAssets(q);if(!assets.length)return {ready:false,state:'unregistered',message:'提示図あり・図の登録待ち'};for(const a of assets){if(a.required_for_attempt!==false){const st=assetStates[a.asset_id];if(!st||st.state!=='displayed')return {ready:false,state:st?.state||'unsaved',message:st?.state==='failed'?'提示図あり・表示できません（再試行）':'提示図あり・表示確認前'}}}return {ready:true,state:'displayed',message:`${assets.length}枚中${assets.length}枚を表示`}}
function createSearchSession(ids,startId){const fixed=[...new Set((ids||[]).filter(Boolean))];return {ids:fixed,startId:fixed.includes(startId)?startId:fixed[0]||null,entries:{}}}
function searchPosition(session,id){const index=session?.ids?.indexOf(id)??-1;return index<0?null:{index,total:session.ids.length,label:`検索結果 ${index+1}/${session.ids.length}`}}
function searchNeighbor(session,id,delta){const pos=searchPosition(session,id);if(!pos)return null;const next=pos.index+delta;return next>=0&&next<pos.total?session.ids[next]:null}
function updateSearchEntry(session,id,draft){if(!searchPosition(session,id))return session;const old=session.entries[id]||{};if(old.attemptId)return session;session.entries[id]={...old,...draft};return session}
function mergeSearchSession(snapshot,latest){return snapshot?.sessionId&&latest?.sessionId===snapshot.sessionId?latest:snapshot}
return {filter,diseaseFacet,departmentCounts,relatedUnique,sameStatus,visibleAssets,attemptReady,createSearchSession,searchPosition,searchNeighbor,updateSearchEntry,mergeSearchSession};});
